### ISSUE TITLE
Add additional files 

### ISSUE THREAD

**Issue by winnidat** [dasistwas/moodle-theme_campus#22]
Can you please implement a section for additonal media files so that we can use the files with direct links in css or in text activities (visibile for every user).

**Comment by gjb2048** [comment]
Who are you please?  I've no idea what you're talking about or where it
should be implemented.

**Comment by winnidat** [comment]
Hi sry, i am a coworker of David. Just add a section in the theme settings where we can upload media files so that than we can use the direct links like theme/image.php/campus/theme/1629361374/background.png or something like that in Custom CSS.

Best regards, Thomas

**Comment by gjb2048** [comment]
Hi Thomas,

I'm Gareth, not sry, does David know about this and has approved me
spending the time please?   Also, I assume it's for the current master
branch.

Gareth

**Comment by gjb2048** [comment]
And how many settings?  One file per setting.

**Comment by winnidat** [comment]
Hi Gareth, 

yeah David has told me you still got some time for us :-). It is for the master_dev version. 
Unlimited files would be best but i guess 10 will do the job (maybe just one file upload box if possible so maybe just the link prefix stays the same). 

Thomas

**Comment by gjb2048** [comment]
Ok, I've just checked and the master branch is old, so the current is
master_dev for Moodle 3.9 as I'm waiting for directions i.e issue #19.
Will need to be a new settings page as core limitation of one file per
setting, so will be ten settings, unless you want it dynamic with the
option of a number of settings setting.

**Comment by winnidat** [comment]
ok then please make a new setting page with a select number off additional files and then load the upload sections according to the number.

Thanks in advance

**Comment by gjb2048** [comment]
So master_dev ok please?  Is there a deadline please!

**Comment by winnidat** [comment]
not really that urgent and master_dev is ok

**Comment by gjb2048** [comment]
@winnidat Thanks, fairly trivial, so will do sooner rather than later.

**Comment by gjb2048** [comment]
@winnidat All done:

![Screenshot 2021-08-20 131108](https://user-images.githubusercontent.com/1058419/130232028-78a55d4e-1c27-4838-b2aa-4d9079392af0.png)

Each file setting will show the stored file URL when set.  I hope this is what you want.

**Comment by winnidat** [comment]
perfect

**Comment by gjb2048** [comment]
@winnidat Just had a thought though with the way that Moodle works and then tested.  It appears that the file URL changes when the settings change / caches are purged!  Therefore I'll have a think and see if there is a better solution to this.

**Comment by gjb2048** [comment]
I think I have a solution!  Will update as soon as I can.

**Comment by gjb2048** [comment]
@winnidat Ok, a solution with a shorter URL that should not change unless the file in the setting changes:

![Screenshot 2021-08-20 144352](https://user-images.githubusercontent.com/1058419/130243086-6b76c4bf-e3ca-4d3a-a30a-a3900362bee6.png)

However, the downside of this (which is why Moodle has implemented their solution in their way) is that the name of the file must change in order for the browser to see that it is different and request it from the server rather than from its own local cache.  Moodle solves this by using the internal theme revision id, however as we've seen, this changes when settings change that clear the theme cache or a 'purge all caches'.  Because I've removed this component from the URL and made it work, then clearly another element in the URL has to change, and that can only be the filename.  The tab heading description now has a 'note' about this.

Hopefully this will now all be fine for you.

**Comment by winnidat** [comment]
Hi Gareth,

thanks a lot i will give feedback on thursday

**Comment by gjb2048** [comment]
Hi Thomas (@winnidat),

Any feedback please?  It's now Friday and you said there would be some on Thursday.

Kind regards,

Gareth

**Comment by winnidat** [comment]
Hi Gareth,

thanks a lot. It  looks fine for me.

Kind regards,
Thomas

**Comment by gjb2048** [comment]
Thanks Thomas.  I have remembered that I did something once with eTags, so might be possible to have 'same filename' but different thing and still be ok if that becomes an issue.
